#LIMPEZA DOS DADOS

In [13]:
import pandas as pd 

df = pd.read_csv(r'atividades_de_extensao.csv')

print(df.columns)

print('\n')

display(df.head(10))


situacao_contagem = df['Situacao'].value_counts()
print('\n')

print(situacao_contagem)

# Lista de situações que são "ruído" e devem sair do DataFrame
situacoes_para_remover = [
    'REMOVIDA', 
    'CADASTRO EM ANDAMENTO', 
    'TEMPO DE CADASTRO EXPIRADO'
]

# Filtra mantendo apenas as linhas cuja situação NÃO ESTÁ (~) na lista de remoção
df_painel = df[~df['Situacao'].isin(situacoes_para_remover)]

print('\n')

# Verifica como ficou o novo tamanho do DataFrame
print(f"\nLinhas antes: {len(df)} | Linhas depois: {len(df_painel)}")

print('\n')

df_painel.info()

Index(['Titulo', 'Codigo', 'Data Inicio', 'Data Fim', 'Unidade', 'Situacao',
       'Fonte Financiamento', 'Data Cadastro', 'Ano Projeto'],
      dtype='str')

,Titulo,Codigo,Data Inicio,Data Fim,Unidade,Situacao,Fonte Financiamento,Data Cadastro,Ano Projeto
0,-,CR0-2019,2019-06-19,2019-06-27,CTDR - DEPARTAMENTO DE TECNOLOGIA DE ALIMENTOS,REMOVIDA,FINANCIAMENTO INTERNO,2019-06-10,2019
1,-,PJ0-2025,2025-11-01,2026-10-31,CT - DEPARTAMENTO DE ARQUITETURA E URBANISMO,REMOVIDA,FINANCIAMENTO INTERNO,2025-09-25,2025
2,.,CR0-2021,2021-10-27,2021-10-30,CT - DEPARTAMENTO DE ENGENHARIA CIVIL E AMBIENTAL,REMOVIDA,FINANCIAMENTO INTERNO,2021-10-25,2021
3,.,PJ0-2023,2023-06-13,2024-06-13,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,REMOVIDA,FINANCIAMENTO INTERNO,2023-06-13,2023
4,.,PJ0-2025,2025-06-18,2025-08-30,CCAE - DEPARTAMENTO DE DESIGN,REMOVIDA,FINANCIAMENTO INTERNO,2025-06-18,2025
5,.,PJ0-2025,2025-11-09,2026-11-09,CCEN - DEPARTAMENTO DE GEOCIÊNCIAS,REMOVIDA,FINANCIAMENTO INTERNO,2025-09-29,2025
6,100 anos do rádio no Brasil - o protagonismo n...,EV114-2019,2019-07-11,2019-07-11,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-07-05,2019
7,10 anos da Licenciatura em Dança da UFPB: traj...,EV110-2023,2023-10-02,2023-12-15,CCTA - DEPARTAMENTO DE ARTES CÊNICAS,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-09-29,2023
8,10 anos do Centro de Tecnologia e Desenvolvime...,EV0-2019,2019-07-03,2019-07-03,CTDR - DEPARTAMENTO DE TECNOLOGIA DE ALIMENTOS,CADASTRO EM ANDAMENTO,FINANCIAMENTO INTERNO,2019-06-19,2019
9,10 anos do Grupo Interdisciplinar de Pesquisa ...,EV96-2022,2022-12-01,2022-12-02,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2022-11-25,2022

Situacao
CONCLUÍDA                                       9314
REMOVIDA                                        1721
PENDENTE DE RELATÓRIO                            984
EM EXECUÇÃO                                      930
CADASTRO EM ANDAMENTO                            624
REPROVADA                                        525
PROJETO CANCELADO                                282
APROVADO SEM RECURSOS                            220
AGUARDANDO APROVAÇÃO DOS DEPARTAMENTOS           142
DESCLASSIFICADO                                   80
NÃO APROVADO PELOS DEPARTAMENTOS                  53
PROPOSTA DEVOLVIDA PARA COORDENADOR REEDITAR      41
AGUARDANDO AVALIAÇÃO                              38
SUBMETIDA                                         31
TEMPO DE CADASTRO EXPIRADO                        17
AVALIAÇÃO REALIZADA                                2
ANALISANDO SOLICITAÇÃO DE RECONSIDERAÇÃO           2
APROVADO COM RECURSOS                              1
REGISTRO APROVADO                                  1
Name: count, dtype: int64



Linhas antes: 15008 | Linhas depois: 12646


<class 'pandas.DataFrame'>
Index: 12646 entries, 6 to 15006
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Titulo               12646 non-null  str
 1   Codigo               12646 non-null  str
 2   Data Inicio          12646 non-null  str
 3   Data Fim             12646 non-null  str
 4   Unidade              12646 non-null  str
 5   Situacao             12646 non-null  str
 6   Fonte Financiamento  12646 non-null  str
 7   Data Cadastro        12646 non-null  str
 8   Ano Projeto          12646 non-null  int64
dtypes: int64(1), str(8)
memory usage: 3.4 MB

CRIAÇÃO DO AGRUPAMENTO DAS SITUAÇÕES

🟢 Concluídos: CONCLUÍDA, PENDENTE DE RELATÓRIO

🔵 Ativos: EM EXECUÇÃO, APROVADO SEM RECURSOS, APROVADO COM RECURSOS

🔴 Cancelados / Reprovados: REPROVADA, PROJETO CANCELADO, DESCLASSIFICADO, NÃO APROVADO PELOS DEPARTAMENTOS

🟡 Em Trâmite (Funil): Todas as outras que sobraram (AGUARDANDO APROVAÇÃO DOS DEPARTAMENTOS, PROPOSTA DEVOLVIDA PARA COORDENADOR REEDITAR, AGUARDANDO AVALIAÇÃO', SUBMETIDA, AVALIAÇÃO REALIZADA, ANALISANDO SOLICITAÇÃO DE RECONSIDERAÇÃO)

In [14]:
import pandas as pd

# 2. Criamos as listas para as nossas categorias principais
concluidos = ['CONCLUÍDA', 'PENDENTE DE RELATÓRIO']
ativos = ['EM EXECUÇÃO', 'APROVADO SEM RECURSOS', 'APROVADO COM RECURSOS']
falhas = ['REPROVADA', 'PROJETO CANCELADO', 'DESCLASSIFICADO', 'NÃO APROVADO PELOS DEPARTAMENTOS']

# 3. Criamos uma função simples para classificar cada linha
def classificar_status(situacao):
    if situacao in concluidos:
        return 'Concluído'
    elif situacao in ativos:
        return 'Ativo'
    elif situacao in falhas:
        return 'Cancelado/Reprovado'
    else:
        return 'Em Trâmite' # O que não caiu nas listas acima, é porque está rodando no sistema

# 4. Criamos a nova coluna aplicando a regra
df_painel['Status_macro'] = df_painel['Situacao'].apply(classificar_status)

display(df_painel.head(10))

,Titulo,Codigo,Data Inicio,Data Fim,Unidade,Situacao,Fonte Financiamento,Data Cadastro,Ano Projeto,Status_macro
6,100 anos do rádio no Brasil - o protagonismo n...,EV114-2019,2019-07-11,2019-07-11,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-07-05,2019,Concluído
7,10 anos da Licenciatura em Dança da UFPB: traj...,EV110-2023,2023-10-02,2023-12-15,CCTA - DEPARTAMENTO DE ARTES CÊNICAS,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-09-29,2023,Concluído
9,10 anos do Grupo Interdisciplinar de Pesquisa ...,EV96-2022,2022-12-01,2022-12-02,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2022-11-25,2022,Concluído
10,10 anos LEPELPB: contribuições à escola públic...,EV222-2019,2019-12-05,2019-12-05,CCS - DEPARTAMENTO DE EDUCAÇÃO FÍSICA,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-10-07,2019,Concluído
11,10º Colóquio de Cinema e Arte da América Latin...,EV99-2024,2024-10-28,2024-11-08,CCTA - DEPARTAMENTO DE JORNALISMO,CONCLUÍDA,FINANCIAMENTO INTERNO,2024-09-09,2024,Concluído
12,11º Encontro de Comunicação Organizacional e R...,EV60-2017,2017-10-19,2017-10-26,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2017-09-25,2017,Concluído
13,11º SIMPÓSIO BRASILEIRO DE CAPTAÇÃO E MANEJO D...,EV0-2018,2018-11-11,2018-11-14,CT - DEPARTAMENTO DE ENGENHARIA CIVIL E AMBIENTAL,AGUARDANDO APROVAÇÃO DOS DEPARTAMENTOS,FINANCIAMENTO INTERNO,2018-11-01,2018,Em Trâmite
14,12º Encontro Internacional de Trompetistas - A...,EV86-2020,2020-11-03,2020-11-08,CCTA - DEPARTAMENTO DE MÚSICA,CONCLUÍDA,FINANCIAMENTO INTERNO,2020-09-29,2020,Concluído
16,&#147; &#147;Disciplina Libras na UFPB: pers...,PJ2-2018,2018-02-19,2018-12-31,CCHLA - DEPARTAMENTO DE LÍNGUAS DE SINAIS,CONCLUÍDA,FINANCIAMENTO INTERNO,2017-10-17,2018,Concluído
18,14° TALENTO CIENTÍFICO JOVEMENTO CIENTÍFICO JOVEM,EV67-2025,2025-07-02,2025-12-31,CCEN - DEPARTAMENTO DE BIOLOGIA MOLECULAR,PENDENTE DE RELATÓRIO,FINANCIAMENTO INTERNO,2025-07-02,2025,Concluído

Transformação das colunas de datas em datas

In [15]:
df_painel.info()

# Lista com as colunas que precisam virar data
colunas_de_data = ['Data Inicio', 'Data Fim', 'Data Cadastro']

# Loop corrigido: deixamos o Pandas identificar o padrão YYYY-MM-DD naturalmente
for coluna in colunas_de_data:
    df_painel[coluna] = pd.to_datetime(df_painel[coluna], errors='coerce')

# Verifique o resultado
df_painel.info()

display(df_painel)

<class 'pandas.DataFrame'>
Index: 12646 entries, 6 to 15006
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Titulo               12646 non-null  str
 1   Codigo               12646 non-null  str
 2   Data Inicio          12646 non-null  str
 3   Data Fim             12646 non-null  str
 4   Unidade              12646 non-null  str
 5   Situacao             12646 non-null  str
 6   Fonte Financiamento  12646 non-null  str
 7   Data Cadastro        12646 non-null  str
 8   Ano Projeto          12646 non-null  int64
 9   Status_macro         12646 non-null  str
dtypes: int64(1), str(9)
memory usage: 3.6 MB
<class 'pandas.DataFrame'>
Index: 12646 entries, 6 to 15006
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Titulo               12646 non-null  str
 1   Codigo               12646 non-null  str
 2   Data Inicio          12646 non-null  datetime64[us]
 3   Data Fim             12646 non-null  datetime64[us]
 4   Unidade              12646 non-null  str
 5   Situacao             12646 non-null  str
 6   Fonte Financiamento  12646 non-null  str
 7   Data Cadastro        12646 non-null  datetime64[us]
 8   Ano Projeto          12646 non-null  int64
 9   Status_macro         12646 non-null  str
dtypes: datetime64[us](3), int64(1), str(6)
memory usage: 3.2 MB

,Titulo,Codigo,Data Inicio,Data Fim,Unidade,Situacao,Fonte Financiamento,Data Cadastro,Ano Projeto,Status_macro
6,100 anos do rádio no Brasil - o protagonismo n...,EV114-2019,2019-07-11,2019-07-11,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-07-05,2019,Concluído
7,10 anos da Licenciatura em Dança da UFPB: traj...,EV110-2023,2023-10-02,2023-12-15,CCTA - DEPARTAMENTO DE ARTES CÊNICAS,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-09-29,2023,Concluído
9,10 anos do Grupo Interdisciplinar de Pesquisa ...,EV96-2022,2022-12-01,2022-12-02,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2022-11-25,2022,Concluído
10,10 anos LEPELPB: contribuições à escola públic...,EV222-2019,2019-12-05,2019-12-05,CCS - DEPARTAMENTO DE EDUCAÇÃO FÍSICA,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-10-07,2019,Concluído
11,10º Colóquio de Cinema e Arte da América Latin...,EV99-2024,2024-10-28,2024-11-08,CCTA - DEPARTAMENTO DE JORNALISMO,CONCLUÍDA,FINANCIAMENTO INTERNO,2024-09-09,2024,Concluído
...,...,...,...,...,...,...,...,...,...,...
14999,YTrad - Traduzindo Yoga para a Comunidade,PJ1632-2025,2025-11-01,2026-10-31,CCHLA - DEPARTAMENTO DE MEDIAÇÕES INTERCULTURAIS,EM EXECUÇÃO,FINANCIAMENTO INTERNO,2025-09-27,2025,Ativo
15002,Zineteca Henrique Magalhães - Educando e Fomen...,PJ0-2023,2023-12-15,2024-12-13,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,REPROVADA,FINANCIAMENTO INTERNO,2023-12-06,2023,Cancelado/Reprovado
15003,Zineteca Henrique Magalhães - Educando e Fomen...,PJ114-2024,2024-05-01,2024-12-15,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2024-04-11,2024,Concluído
15005,Zoneamento da ambiental para Ecoturismo de Vis...,PJ193-2023,2023-05-26,2023-12-31,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-04-24,2023,Concluído
15006,Zoneamento edafoclimático do café no município...,PJ0-2025,2025-07-01,2025-12-31,CCA - DEPARTAMENTO DE SOLOS E ENGENHARIA RURAL,SUBMETIDA,FINANCIAMENTO INTERNO,2025-05-09,2025,Em Trâmite

CRIAR TIPOS DE AÇÕES

In [16]:
# 1. Criamos um dicionário com as regras que você definiu
dicionario_acoes = {
    'EV': 'Evento',
    'CR': 'Curso',
    'PD': 'Produto',
    'PG': 'Programa',
    'PJ': 'Projeto'
}

# 2. Pegamos apenas as 2 primeiras letras da coluna 'Codigo'
# O .str[:2] significa: "pegue o texto do início até o segundo caractere"
letras_iniciais = df_painel['Codigo'].str[:2]

# 3. Mapeamos essas letras para os nomes completos e criamos a nova coluna
df_painel['Tipo de Ação'] = letras_iniciais.map(dicionario_acoes)

# 4. (Opcional de Segurança) Caso exista algum código fora desse padrão na base, 
# ele ficaria nulo. Podemos preencher com "OUTROS" para não estragar o painel:
df_painel['Tipo de Ação'] = df_painel['Tipo de Ação'].fillna('OUTROS')

# 5. Verificamos o resultado da nossa nova categorização
print("Quantidade de ações por tipo:")
print(df_painel['Tipo de Ação'].value_counts())

display(df_painel)

Quantidade de ações por tipo:
Tipo de Ação
Projeto     9360
Curso       1765
Evento      1363
Produto      125
Programa      33
Name: count, dtype: int64

,Titulo,Codigo,Data Inicio,Data Fim,Unidade,Situacao,Fonte Financiamento,Data Cadastro,Ano Projeto,Status_macro,Tipo de Ação
6,100 anos do rádio no Brasil - o protagonismo n...,EV114-2019,2019-07-11,2019-07-11,CCTA - DEPARTAMENTO DE COMUNICAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-07-05,2019,Concluído,Evento
7,10 anos da Licenciatura em Dança da UFPB: traj...,EV110-2023,2023-10-02,2023-12-15,CCTA - DEPARTAMENTO DE ARTES CÊNICAS,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-09-29,2023,Concluído,Evento
9,10 anos do Grupo Interdisciplinar de Pesquisa ...,EV96-2022,2022-12-01,2022-12-02,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2022-11-25,2022,Concluído,Evento
10,10 anos LEPELPB: contribuições à escola públic...,EV222-2019,2019-12-05,2019-12-05,CCS - DEPARTAMENTO DE EDUCAÇÃO FÍSICA,CONCLUÍDA,FINANCIAMENTO INTERNO,2019-10-07,2019,Concluído,Evento
11,10º Colóquio de Cinema e Arte da América Latin...,EV99-2024,2024-10-28,2024-11-08,CCTA - DEPARTAMENTO DE JORNALISMO,CONCLUÍDA,FINANCIAMENTO INTERNO,2024-09-09,2024,Concluído,Evento
...,...,...,...,...,...,...,...,...,...,...,...
14999,YTrad - Traduzindo Yoga para a Comunidade,PJ1632-2025,2025-11-01,2026-10-31,CCHLA - DEPARTAMENTO DE MEDIAÇÕES INTERCULTURAIS,EM EXECUÇÃO,FINANCIAMENTO INTERNO,2025-09-27,2025,Ativo,Projeto
15002,Zineteca Henrique Magalhães - Educando e Fomen...,PJ0-2023,2023-12-15,2024-12-13,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,REPROVADA,FINANCIAMENTO INTERNO,2023-12-06,2023,Cancelado/Reprovado,Projeto
15003,Zineteca Henrique Magalhães - Educando e Fomen...,PJ114-2024,2024-05-01,2024-12-15,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,CONCLUÍDA,FINANCIAMENTO INTERNO,2024-04-11,2024,Concluído,Projeto
15005,Zoneamento da ambiental para Ecoturismo de Vis...,PJ193-2023,2023-05-26,2023-12-31,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,CONCLUÍDA,FINANCIAMENTO INTERNO,2023-04-24,2023,Concluído,Projeto
15006,Zoneamento edafoclimático do café no município...,PJ0-2025,2025-07-01,2025-12-31,CCA - DEPARTAMENTO DE SOLOS E ENGENHARIA RURAL,SUBMETIDA,FINANCIAMENTO INTERNO,2025-05-09,2025,Em Trâmite,Projeto

In [17]:
import pandas as pd
import re

# 1. Dicionário com as siglas e os nomes exatamente como você pediu
dicionario_centros = {
    'CBIOTEC': 'CBiotec - Centro de Biotecnologia',
    'CCEN': 'CCEN - Centro de Ciências Exatas',
    'CCHLA': 'CCHLA - Centro de Ciências Humanas e Letras',
    'CCJ': 'CCJ - Centro de Ciências Jurídicas',
    'CCM': 'CCM - Centro de Ciências Médicas',
    'CCS': 'CCS - Centro de Ciências da Saúde',
    'CCSA': 'CCSA - Centro de Ciências Sociais Aplicadas',
    'CCTA': 'CCTA - Centro de Comunicação e Artes',
    'CEAR': 'CEAR - Centro de Energias Renováveis',
    'CE': 'CE - Centro de Educação',
    'CI': 'CI - Centro de Informática',
    'CTDR': 'CTDR - Centro de Tecnologia e Desenvolvimento Regional',
    'CT': 'CT - Centro de Tecnologia',
    'CCA': 'CCA - Centro de Ciências Agrárias',
    'CCHSA': 'CCHSA - Centro de Ciências Humanas, Sociais e Agrárias',
    'CCAE': 'CCAE - Centro de Ciências Aplicadas e Educação'
}

# 2. Função inteligente para achar a sigla exata (evitando que "CI" confunda com "CIÊNCIAS")
def extrair_centro(unidade_texto):
    texto = str(unidade_texto).upper()
    
    # Testa cada sigla do nosso dicionário
    for sigla, nome_formatado in dicionario_centros.items():
        # O \b significa "fronteira de palavra". Ele garante que só vai achar a sigla isolada.
        if re.search(rf'\b{sigla}\b', texto):
            return nome_formatado
            
    # Se não achar nenhuma sigla da UFPB, retorna o conteúdo original da unidade
    return unidade_texto

# 3. Aplicando a função para criar a nova coluna
df_painel['Centro de Ensino'] = df_painel['Unidade'].apply(extrair_centro)

#ajustar a ordem das colunas

ordem_colunas = [
    'Ano Projeto', 
    'Codigo', 
    'Tipo de Ação', 
    'Titulo', 
    'Centro de Ensino',
    'Unidade', 
    'Data Inicio', 
    'Data Fim',  
    'Situacao', 
    'Status_macro',  
    'Fonte Financiamento'
]

# 3. Aplicar a nova ordem (isso também vai ocultar colunas indesejadas que não estão na lista)
df_painel = df_painel[ordem_colunas]

# 4. Restringindo a Análise Histórica (Apenas de 2020 a 2025)
# Mantém apenas os projetos onde o ano é maior ou igual a 2020 E menor ou igual a 2025
df_historico = df_painel[(df_painel['Ano Projeto'] >= 2020) & (df_painel['Ano Projeto'] <= 2025)].copy()

# 5. Sobrescrevendo o arquivo CSV do Painel com a base nova
caminho_exato = r'G:\Meu Drive\Curso_hastag\Projeto Integrador II\base_painel_2020_2025.csv'
df_historico.to_csv(caminho_exato, index=False, encoding='utf-8')

print("Transformações concluídas!")
print(f"Total de projetos filtrados (2020 a 2025): {len(df_historico)}")
print("A coluna 'CENTRO DE ENSINO' foi criada e o CSV foi atualizado.")

display(df_historico)

Transformações concluídas!
Total de projetos filtrados (2020 a 2025): 8771
A coluna 'CENTRO DE ENSINO' foi criada e o CSV foi atualizado.

,Ano Projeto,Codigo,Tipo de Ação,Titulo,Centro de Ensino,Unidade,Data Inicio,Data Fim,Situacao,Status_macro,Fonte Financiamento
7,2023,EV110-2023,Evento,10 anos da Licenciatura em Dança da UFPB: traj...,CCTA - Centro de Comunicação e Artes,CCTA - DEPARTAMENTO DE ARTES CÊNICAS,2023-10-02,2023-12-15,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
9,2022,EV96-2022,Evento,10 anos do Grupo Interdisciplinar de Pesquisa ...,CCEN - Centro de Ciências Exatas,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,2022-12-01,2022-12-02,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
11,2024,EV99-2024,Evento,10º Colóquio de Cinema e Arte da América Latin...,CCTA - Centro de Comunicação e Artes,CCTA - DEPARTAMENTO DE JORNALISMO,2024-10-28,2024-11-08,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
14,2020,EV86-2020,Evento,12º Encontro Internacional de Trompetistas - A...,CCTA - Centro de Comunicação e Artes,CCTA - DEPARTAMENTO DE MÚSICA,2020-11-03,2020-11-08,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
18,2025,EV67-2025,Evento,14° TALENTO CIENTÍFICO JOVEMENTO CIENTÍFICO JOVEM,CCEN - Centro de Ciências Exatas,CCEN - DEPARTAMENTO DE BIOLOGIA MOLECULAR,2025-07-02,2025-12-31,PENDENTE DE RELATÓRIO,Concluído,FINANCIAMENTO INTERNO
...,...,...,...,...,...,...,...,...,...,...,...
14999,2025,PJ1632-2025,Projeto,YTrad - Traduzindo Yoga para a Comunidade,CCHLA - Centro de Ciências Humanas e Letras,CCHLA - DEPARTAMENTO DE MEDIAÇÕES INTERCULTURAIS,2025-11-01,2026-10-31,EM EXECUÇÃO,Ativo,FINANCIAMENTO INTERNO
15002,2023,PJ0-2023,Projeto,Zineteca Henrique Magalhães - Educando e Fomen...,CE - Centro de Educação,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,2023-12-15,2024-12-13,REPROVADA,Cancelado/Reprovado,FINANCIAMENTO INTERNO
15003,2024,PJ114-2024,Projeto,Zineteca Henrique Magalhães - Educando e Fomen...,CE - Centro de Educação,CE - DEPARTAMENTO DE FUNDAMENTAÇÃO DA EDUCAÇÃO,2024-05-01,2024-12-15,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
15005,2023,PJ193-2023,Projeto,Zoneamento da ambiental para Ecoturismo de Vis...,CCEN - Centro de Ciências Exatas,CCEN - DEPARTAMENTO DE SISTEMÁTICA E ECOLOGIA,2023-05-26,2023-12-31,CONCLUÍDA,Concluído,FINANCIAMENTO INTERNO
15006,2025,PJ0-2025,Projeto,Zoneamento edafoclimático do café no município...,CCA - Centro de Ciências Agrárias,CCA - DEPARTAMENTO DE SOLOS E ENGENHARIA RURAL,2025-07-01,2025-12-31,SUBMETIDA,Em Trâmite,FINANCIAMENTO INTERNO

SALVAR ARQUIVO FINAL

In [18]:
# Adicionando a pasta OneDrive no caminho
caminho_exato = r'C:\Users\danil\OneDrive\Desktop\base_painel_2020_2025.csv'

df_historico.to_csv(caminho_exato, index=False, encoding='utf-8')
print("Arquivo salvo com sucesso na Área de Trabalho do OneDrive!")

Arquivo salvo com sucesso na Área de Trabalho do OneDrive!